import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const howtoDir = resolve(__dirname, '../../howto')
const outFile  = resolve(__dirname, '../src/howto-content.js')

const topics = [
  { key: 'check-car-in',    file: 'check-car-in.md'    },
  { key: 'check-car-out',   file: 'check-car-out.md'   },
  { key: 'add-client',      file: 'add-client.md'      },
  { key: 'scan-new-vin',    file: 'scan-new-vin.md'    },
  { key: 'add-staff-user',  file: 'add-staff-user.md'  },
  { key: 'export-data',     file: 'export-data.md'     },
]

const entries = topics.map(({ key, file }) => {
  const content = readFileSync(resolve(howtoDir, file), 'utf8').trim()
  return `  '${key}': ${JSON.stringify(content)}`
})

const output = `// Auto-generated by scripts/sync-howto.js — do not edit directly.
// Edit the source files in /kiln/claude/clearpath/glenbarry/howto/ and re-run the script.
const HOWTO_CONTENT = {
${entries.join(',\n')}
}

export default HOWTO_CONTENT
`

writeFileSync(outFile, output)
console.log('howto-content.js updated.')
